import { Component, OnInit, Input, AfterViewInit, OnChanges, SimpleChanges, AfterViewChecked } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { AgentassignmentService } from '../../services/agentassignment.service';

@Component({
  selector: 'app-searchcriteria',
  templateUrl: './searchcriteria.component.html',
  styleUrls: ['./searchcriteria.component.scss']
})
export class SearchcriteriaComponent implements OnInit, AfterViewInit, OnChanges, AfterViewChecked  {
  searchRecordComponent;
  detailSearchRecordComponent;

  searchForm;
  dropDownInitialized: boolean = false;

  minDateTo;
  maxDateFrom;
  @Input()currSubPage;

  constructor(
    private agentassignmentService : AgentassignmentService
  ) {}

  ngOnInit() {}

  //get funcs
  //agentassign page
  get fullName(){return this.searchForm.get("fullName");}
  get policyNo(){return this.searchForm.get("policyNo");}
  get mobileNo(){return this.searchForm.get("mobileNo");}
  get emailAddr(){return this.searchForm.get("emailAddr");}
  get idCardNo(){return this.searchForm.get("idCardNo");}
  get dateOfSubmissionFrom(){return this.searchForm.get("dateOfSubmissionFrom");}
  get dateOfSubmissionTo(){return this.searchForm.get("dateOfSubmissionTo");}
  get assignmentOption(){return this.searchForm.get("assignmentOption");}
  //agentdetail page
  get agentCode(){return this.searchForm.get("agentCode");}
  get agentPhone(){return this.searchForm.get("agentPhone");}
  get agentName(){return this.searchForm.get("agentName");}

  ngOnChanges(changes: SimpleChanges){
    console.log('Info: Search Criteria component onchanges, ', changes, "this.currSubPage:", this.currSubPage);
    let phoneNoValidator = [Validators.pattern('[0-9]+'), Validators.maxLength(8), Validators.minLength(8)];
    this.searchForm = (this.currSubPage === 'easAgentAssignGI') ?
    new FormGroup({
      fullName : new FormControl(''),
      policyNo : new FormControl(''),
      mobileNo : new FormControl('',phoneNoValidator),
      emailAddr : new FormControl('', Validators.email),
      idCardNo : new FormControl(''),
      dateOfSubmissionFrom : new FormControl(''),
      dateOfSubmissionTo : new FormControl(''),
      assignmentOption : new FormControl('')
    }) : (this.currSubPage === 'easAgentAssignCS') ? new FormGroup({
      fullName : new FormControl(''),
      policyNo : new FormControl(''),
      mobileNo : new FormControl('',phoneNoValidator),
      emailAddr : new FormControl('', Validators.email),
      idCardNo : new FormControl(''),
      dateOfSubmissionFrom : new FormControl(''),
      dateOfSubmissionTo : new FormControl(''),
      assignmentOption : new FormControl(''),
      contactCustomerOption : new FormControl(''),
      assignmentStatusOption : new FormControl('')
    }) : new FormGroup({
     agentCode : new FormControl(''),
     agentPhone : new FormControl('',phoneNoValidator),
     agentName : new FormControl('')
   });
   this.dropDownInitialized = (['easAgentAssignCS','easAgentAssignGI'].indexOf(this.currSubPage) !== -1) ?
    false : this.dropDownInitialized;
  }
  //search criteria's drop down is dynamically generated by jquery
  //and should be called when the subpage has just changed
  initDropdown(fieldName){
    let divFieldName = `.div-` + fieldName + ` `;
    $("[name=" + fieldName + "Field]").val("A"); //initialize the select into default val first
    $(divFieldName + ".select-items div:eq(0)").addClass("same-as-selected");
    $(divFieldName + ".select-selected").text($(divFieldName + ".select-items div:eq(0)").text());
    //select-selected select-arrow-active
    //select-hide, same-as-selected
    $(divFieldName + ".select-selected").on("click", ()=>{
      $(divFieldName + ".select-items").removeClass("select-hide");
      $(divFieldName + ".select-selected").addClass("select-arrow-active");
    });
    //
    let selectOptionNameMapVal = {}; //select option name map to val
    for(var i = 0; i < $("[name=" + fieldName + "Field] option").length; i++){
      let currOption = $("[name=" + fieldName + "Field] option:eq(" + i + ")");
      selectOptionNameMapVal[currOption.html()] = currOption.val();
    }
    //register event for div
    let selectItemsChildren = $(divFieldName + '.select-items').children();
    for(var j = 0; j < selectItemsChildren.length; j++){
      $(divFieldName + ".select-items div:eq(" + j + ")").on('click', (e)=>{
        $(divFieldName + ".select-selected").removeClass("select-arrow-active");
        $(divFieldName + ".select-selected").text($(e.target).text());
        $(divFieldName + ".select-items").addClass("select-hide");
        for(var k = 0; k < selectItemsChildren.length; k++){
          $(divFieldName + ".select-items div:eq(" + k + ")").removeClass("same-as-selected");
        }
        $(e.target).addClass("same-as-selected");

        $("[name='" + fieldName + "Field']").val(
          selectOptionNameMapVal[$(e.target).text()]
        );
      });
    }
  }
  ngAfterViewInit(){
    if(this.currSubPage === 'easAgentAssignGI'){
      this.initDropdown('assignmentOption'); //the 'assignment' dropdown is dynamically generated
    }else{
      this.initDropdown('assignmentOption'); //the 'assignment' dropdown is dynamically generated
      this.initDropdown('contactCustomerOption'); //the 'assignment' dropdown is dynamically generated
      this.initDropdown('assignmentStatusOption'); //the 'assignment' dropdown is dynamically generated
    }
  }
  ngAfterViewChecked(){
    if(!this.dropDownInitialized){
      if(this.currSubPage === 'easAgentAssignGI'){
        this.initDropdown('assignmentOption'); //the 'assignment' dropdown is dynamically generated
      }else{
        this.initDropdown('assignmentOption'); //the 'assignment' dropdown is dynamically generated
        this.initDropdown('contactCustomerOption'); //the 'assignment' dropdown is dynamically generated
        this.initDropdown('assignmentStatusOption'); //the 'assignment' dropdown is dynamically generated
      }
      this.dropDownInitialized = true;
    }
  }
  //to set the min, max date of from / to once submissionfrom / to is changed
  dateOfSubmissionChange(e, fromOrTo){
    this[(fromOrTo == 0) ? "minDateTo" : "maxDateFrom"] = e.value;
  }

  onSubmitSearchCriteria(){
    let fullName,policyNo,mobileNo,emailAddr,idCardNo,dateOfSubmissionFrom,dateOfSubmissionTo,assignmentOption,
    agentCode,agentPhone,agentName, queryParams;
    //angular form cannot read value of a select elm which is being controlled by div and jquery
    //has to use jquery to read the div value and overwrite the search criterias sent
    //to searchRecordComponent first
    assignmentOption = "";
    let isAgentAssign = ['easAgentAssignCS','easAgentAssignGI'].indexOf(this.currSubPage) !== -1;
    for(var i = 0 ; i < $('.select-items div').length; i++){
      if($('.select-items div:eq(' + i + ')').hasClass('same-as-selected')){
        assignmentOption = $('[name="assignmentOptionField"] option:eq('+ i +')').html();
        break;
      }
    }

    if(isAgentAssign){
      ({fullName,policyNo,mobileNo,emailAddr,idCardNo,dateOfSubmissionFrom,dateOfSubmissionTo} = this.searchForm.value);
      queryParams = {fullName,policyNo,mobileNo,emailAddr,idCardNo,dateOfSubmissionFrom,dateOfSubmissionTo};
    }else{
      ({agentCode, agentPhone, agentName} = this.searchForm.value);
      queryParams = {agentCode, agentPhone, agentName};
    }
    //transform the raw date to formatted locale date string YYYY/MM/DD
    dateOfSubmissionFrom = !dateOfSubmissionFrom ? dateOfSubmissionFrom : new Date(dateOfSubmissionFrom).toLocaleDateString();
    dateOfSubmissionTo = !dateOfSubmissionTo ? dateOfSubmissionTo : new Date(dateOfSubmissionTo).toLocaleDateString();

    let searchCriteriaArr = (isAgentAssign) ?
    [fullName,policyNo,mobileNo,emailAddr,idCardNo,dateOfSubmissionFrom,dateOfSubmissionTo,assignmentOption] :
    [agentCode, agentPhone, agentName];

    let property = (isAgentAssign) ? "searchRecordComponent" : "detailSearchRecordComponent";
    // console.log("queryParams:", queryParams)
    // Object.keys(queryParams).forEach((elem, index)=>{
    //   this[property].searchCriteria[index] = elem;
    // })

    this[property].refreshAndReloadSearchRecordTable(searchCriteriaArr);
  }

  setSearchRecordComponent(searchRecordComponent){ //ngif in the comps, they wouldnt be automatically assigned
    let property = (['easAgentAssignCS','easAgentAssignGI'].indexOf(this.currSubPage) !== -1) ? "searchRecordComponent" : "detailSearchRecordComponent";
    this[property] = searchRecordComponent;
  }
}
